lowerCase = """{py.K_0: '0', py.K_1: '1', py.K_2: '2', py.K_3: '3',
             py.K_4: '4', py.K_5: '5', py.K_6: '6', py.K_7: '7',
             py.K_8: '8', py.K_9: '9', py.K_AMPERSAND: '&',
             py.K_ASTERISK: '*', py.K_AT: '@', py.K_BACKQUOTE: '`',
             py.K_BACKSLASH: '\\\\', py.K_BACKSPACE: 'DEL',
             py.K_BREAK: '', py.K_CAPSLOCK: '', py.K_CARET: '^',
             py.K_CLEAR: '', py.K_COLON: ':', py.K_COMMA: ',',
             py.K_DELETE: 'DEL', py.K_DOLLAR: '$', py.K_DOWN: '',
             py.K_END: '', py.K_EQUALS: '=', py.K_ESCAPE: '',
             py.K_EURO: '', py.K_EXCLAIM: '!', py.K_F1: '',
             py.K_F10: '', py.K_F11: '', py.K_F12: '',
             py.K_F13: '', py.K_F14: '', py.K_F15: '',
             py.K_F2: '', py.K_F3: '', py.K_F4: '', py.K_F5: '',
             py.K_F6: '', py.K_F7: '', py.K_F8: '', py.K_F9: '',
             py.K_FIRST: '', py.K_GREATER: '>', py.K_HASH: '#',
             py.K_HELP: '', py.K_HOME: '', py.K_INSERT: '',
             py.K_KP0: '0', py.K_KP1: '1', py.K_KP2: '2',
             py.K_KP3: '3', py.K_KP4: '4', py.K_KP5: '5',
             py.K_KP6: '6', py.K_KP7: '7', py.K_KP8: '8',
             py.K_KP9: '9', py.K_KP_DIVIDE: '/',
             py.K_KP_ENTER: '\\n', py.K_KP_EQUALS: '=',
             py.K_KP_MINUS: '-', py.K_KP_MULTIPLY: '*',
             py.K_KP_PERIOD: '.', py.K_KP_PLUS: '+',
             py.K_LALT: '', py.K_LAST: '', py.K_LCTRL: '', py.K_LEFT: '',
             py.K_LEFTBRACKET: '[', py.K_LEFTPAREN: '(', py.K_LESS: '<',
             py.K_LMETA: '', py.K_LSHIFT: '', py.K_LSUPER: '',
             py.K_MENU: '', py.K_MINUS: '-', py.K_MODE: '', py.K_NUMLOCK: '',
             py.K_PAGEDOWN: '', py.K_PAGEUP: '', py.K_PAUSE: '',
             py.K_PERIOD: '.', py.K_PLUS: '+', py.K_POWER: '', py.K_PRINT: '',
             py.K_QUESTION: '?', py.K_QUOTE: "'", py.K_QUOTEDBL: '"',
             py.K_RALT: '', py.K_RCTRL: '', py.K_RETURN: '\\n',
             py.K_RIGHT: '', py.K_RIGHTBRACKET: ']', py.K_RIGHTPAREN: ')',
             py.K_RMETA: '', py.K_RSHIFT: '', py.K_RSUPER: '',
             py.K_SCROLLOCK: '', py.K_SEMICOLON: ';', py.K_SLASH: '/',
             py.K_SPACE: ' ', py.K_SYSREQ: '', py.K_TAB: '\\t',
             py.K_UNDERSCORE: '_', py.K_UNKNOWN: '???', py.K_UP: '',
             py.K_a: 'a', py.K_b: 'b', py.K_c: 'c', py.K_d: 'd',
             py.K_e: 'e', py.K_f: 'f', py.K_g: 'g', py.K_h: 'h',
             py.K_i: 'i', py.K_j: 'j', py.K_k: 'k', py.K_l: 'l',
             py.K_m: 'm', py.K_n: 'n', py.K_o: 'o', py.K_p: 'p',
             py.K_q: 'q', py.K_r: 'r', py.K_s: 's', py.K_t: 't',
             py.K_u: 'u', py.K_v: 'v', py.K_w: 'w', py.K_x: 'x',
             py.K_y: 'y', py.K_z: 'z'
             }"""

upperCase = """{py.K_0: ')', py.K_1: '!', py.K_2: '@', py.K_3: '#',
             py.K_4: '$', py.K_5: '%', py.K_6: '^', py.K_7: '&',
             py.K_8: '*', py.K_9: '(', py.K_AMPERSAND: '&',
             py.K_ASTERISK: '*', py.K_AT: '@', py.K_BACKQUOTE: '~',
             py.K_BACKSLASH: '|', py.K_BACKSPACE: 'DEL',
             py.K_BREAK: '', py.K_CAPSLOCK: '', py.K_CARET: '^',
             py.K_CLEAR: '', py.K_COLON: ':', py.K_COMMA: '<',
             py.K_DELETE: 'DEL', py.K_DOLLAR: '$', py.K_DOWN: '',
             py.K_END: '', py.K_EQUALS: '+', py.K_ESCAPE: '',
             py.K_EURO: '', py.K_EXCLAIM: '!', py.K_F1: '',
             py.K_F10: '', py.K_F11: '', py.K_F12: '',
             py.K_F13: '', py.K_F14: '', py.K_F15: '',
             py.K_F2: '', py.K_F3: '', py.K_F4: '', py.K_F5: '',
             py.K_F6: '', py.K_F7: '', py.K_F8: '', py.K_F9: '',
             py.K_FIRST: '', py.K_GREATER: '>', py.K_HASH: '#',
             py.K_HELP: '', py.K_HOME: '', py.K_INSERT: '',
             py.K_KP0: '0', py.K_KP1: '1', py.K_KP2: '2',
             py.K_KP3: '3', py.K_KP4: '4', py.K_KP5: '5',
             py.K_KP6: '6', py.K_KP7: '7', py.K_KP8: '8',
             py.K_KP9: '9', py.K_KP_DIVIDE: '/',
             py.K_KP_ENTER: '\\n', py.K_KP_EQUALS: '=',
             py.K_KP_MINUS: '-', py.K_KP_MULTIPLY: '*',
             py.K_KP_PERIOD: '.', py.K_KP_PLUS: '+',
             py.K_LALT: '', py.K_LAST: '', py.K_LCTRL: '', py.K_LEFT: '',
             py.K_LEFTBRACKET: '{', py.K_LEFTPAREN: '(', py.K_LESS: '<',
             py.K_LMETA: '', py.K_LSHIFT: '', py.K_LSUPER: '',
             py.K_MENU: '', py.K_MINUS: '_', py.K_MODE: '', py.K_NUMLOCK: '',
             py.K_PAGEDOWN: '', py.K_PAGEUP: '', py.K_PAUSE: '',
             py.K_PERIOD: '>', py.K_PLUS: '+', py.K_POWER: '', py.K_PRINT: '',
             py.K_QUESTION: '?', py.K_QUOTE: '"', py.K_QUOTEDBL: '"',
             py.K_RALT: '', py.K_RCTRL: '', py.K_RETURN: '\\n',
             py.K_RIGHT: '', py.K_RIGHTBRACKET: '}', py.K_RIGHTPAREN: ')',
             py.K_RMETA: '', py.K_RSHIFT: '', py.K_RSUPER: '',
             py.K_SCROLLOCK: '', py.K_SEMICOLON: ':', py.K_SLASH: '?',
             py.K_SPACE: ' ', py.K_SYSREQ: '', py.K_TAB: '\\t',
             py.K_UNDERSCORE: '_', py.K_UNKNOWN: '???', py.K_UP: '',
             py.K_a: 'A', py.K_b: 'B', py.K_c: 'C', py.K_d: 'D',
             py.K_e: 'E', py.K_f: 'F', py.K_g: 'G', py.K_h: 'H',
             py.K_i: 'I', py.K_j: 'J', py.K_k: 'K', py.K_l: 'L',
             py.K_m: 'M', py.K_n: 'N', py.K_o: 'O', py.K_p: 'P',
             py.K_q: 'Q', py.K_r: 'R', py.K_s: 'S', py.K_t: 'T',
             py.K_u: 'U', py.K_v: 'V', py.K_w: 'W', py.K_x: 'X',
             py.K_y: 'Y', py.K_z: 'Z'
             }"""


